config/routes.rb
Rails.application.routes.draw do
  resources :gifs, only: [ :index, :show ] do
    resources :favorites, only: [:new, :create, :destroy]
  end


  resources :categories, param: :name,  only: [ :show, :index ]

  resources :users, only: [ :new, :create, :show ]

  namespace :admin do
    resources :gifs, only: [ :new, :create ]
  end

  get '/login', to: "sessions#new"
  post '/login', to: "sessions#create"
  delete '/logout', to: "sessions#destroy"


end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :gifs
  validates :name, presence: true, uniqueness: true

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base
  belongs_to :gif
  belongs_to :user
end

app/models/gif.rb
class Gif < ActiveRecord::Base
  belongs_to :category
  has_many :favorites
  has_many :users, through: :favorites

  validates :image_path, presence: true, uniqueness: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  has_many :favorites
  has_many :gifs, through: :favorites
  validates :username, presence: true, uniqueness: true
  validates :password, presence: true
  enum role: %w(default admin)
  scope :admin?, -> { where(role: 1) }
end

app/controllers/admin/gifs_controller.rb
class Admin::GifsController < ApplicationController
  before_action :require_admin

  include ApplicationHelper

  def new
  end

  def create
    category = Category.create(name: params[:category_name])
    gifs = all_gifs(params[:category_name])

    gifs.each do |gif_path|
      Gif.create(image_path: gif_path, category_id: category.id)
    end

    redirect_to categories_path
  end

  def require_admin
    unless current_user.admin?
      redirect_to "../../public/404"
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :user_logged_in?, :current_user

  def user_logged_in?
    !session[:user_id].nil?
  end

  def current_user
      @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def show
    @category = Category.find(params[:name])
  end

  def index
    @categories = Category.all
  end

end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def new
  end

  def create
    current_user.favorites.create(user_id: :id, gif_id: params[:gif_id])

    redirect_to gifs_path
  end

  def destroy
    current_user.favorites.find_by(params[:id]).delete
    redirect_to user_path(current_user)
  end

end

app/controllers/gifs_controller.rb
class GifsController < ApplicationController

  def index
    @gifs = Gif.all
  end

  def show
    @gif = Gif.find(params[:id])
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Success"
      redirect_to user_path(user)
    else
      flash[:alert] = "Invalid Login"
      render :new
    end
  end

  def destroy
    session.clear
    redirect_to gifs_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include UsersHelper

  def new
    @user = User.new
  end

  def show
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)

    if @user.save
      flash[:success] = "Success. Please Log In"
      redirect_to login_path
    else
      flash[:alert] = "Alert: Username/Password is Invalid"
      render :new
    end
  end


  private

  def user_params
    params.require(:user).permit(:username, :password)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

    def all_gifs(category)
      if category.split.count > 1
        category = category.split.join("+")
      end
      response = Faraday.get("http://api.giphy.com/v1/gifs/search?q=#{category}&api_key=dc6zaTOxFJmzC")
      data = JSON.parse(response.body)
      get_paths(data)
    end

    def get_paths(data)
    data["data"].map do |data|
      data["images"]["fixed_height"]["url"]
      end
    end
end

app/helpers/gifs_helper.rb
module GifsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  def favorite_id(user_id, gif_id)
    User.find(user_id).favorites.find_by(user_id: user_id, gif_id: gif_id).id
  end

end

app/views/admin/gifs/new.html.haml
%h1.text-center Add New Gifs!

.row.small-6.small-centered.columns
  =form_tag("/admin/gifs", method: "post") do
    = label_tag :category_name, "Category Name"
    = text_field_tag :category_name
    = submit_tag "Create Gifs!"

app/views/categories/index.html.haml
%h1.row.small-6.small-centered.columns All The Categories


.row
- @categories.each do |category|
  .small-4.float-right.columns.thumbnail= link_to(image_tag(category.gifs.sample.image_path), category_path(category))
  .float-right= link_to(category.name, category_path(category))

app/views/categories/show.html.haml
%h1.row.small-2.small-centered.columns= @category.name

.row.small-up-1.medium-up-2.large-up-3
  - @category.gifs.each do |gif|
    .column.thumbnail= link_to(image_tag(gif.image_path, alt: gif.image_path), gif_path(gif))

app/views/gifs/index.html.haml
%h1.row.small-3.small-centered.columns All The Gifs

.row.small-up-1.medium-up-2.large-up-3
  - @gifs.shuffle.each do |gif|
    .column.thumbnail= link_to(image_tag(gif.image_path, alt: gif.image_path), gif_path(gif))

app/views/gifs/show.html.haml
.row
  .small-6.small-centered.columns= image_tag @gif.image_path
  %b.success-button= button_to "Favorite", gif_favorites_path(@gif.id)
.row
  %h5.small-3.small-centered.columns= link_to @gif.category.name, @gif.category

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GifGenerator</title>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/foundation/6.2.1/foundation.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <div><%= render partial: "/partials/nav" %></div>
    <div><%= render partial: "/partials/flash_notice" %></div>
    <%= yield %>
</body>
<script src="https://cdn.jsdelivr.net/foundation/6.2.1/foundation.min.js"></script>
</html>

app/views/partials/_flash_notice.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="<%= name %> callout" data-closable>
      <%= content_tag :div, msg, class: "text-center"%>
      <button class="close-button" aria-label="Dismiss alert" type="button" data-close>
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>
<% end %>

app/views/partials/_nav.html.erb
<div class="top-bar">
  <div class="top-bar-title"><%= link_to "Gif Explosion", gifs_path, {style: "color: purple"} %></div>
  <div>
    <div class="top-bar-left"></div>
      <%= link_to "Categories", categories_path %>
    <div class="top-bar-right">
      <%= link_to "User Dashboard", user_path(current_user) if user_logged_in? %>
      <%= link_to "Log Out", logout_path, method: :delete if user_logged_in? %>
      <%= link_to "Create Account", new_user_path unless user_logged_in? %>
      <%= link_to "Log In", login_path unless user_logged_in? %>
    </div>
  </div>
</div>

app/views/users/new.html.haml
.row.small-6.small-centered.columns
  =form_for @user do |f|
    = f.label :username
    = f.text_field :username
    = f.label :password
    = f.password_field :password

    = f.submit 

app/views/users/show.html.haml
.row.small-6.small-centered.columns
  %h1= "Welcome " + @user.username
  %b= link_to "Create Gif", new_admin_gif_path if @user.admin?
  %h4 Your Gifs
.row.small-up-1.medium-up-2.large-up-3
  - @user.gifs.each do |gif|
    .column.thumbnail= image_tag(gif.image_path, alt: gif.image_path)
    %b.alert-button= button_to "Unfavorite", gif_favorite_path(gif.id, favorite_id(@user.id, gif.id)), method: :delete